
const loru =[
"REVENUEPERSHARETTM",
"NETINCOMEPERSHARETTM",
"OPERATINGCASHFLOWPERSHARETTM",
"FREECASHFLOWPERSHARETTM",
"CASHPERSHARETTM",
"BOOKVALUEPERSHARETTM",
"TANGIBLEBOOKVALUEPERSHARETTM",
"SHAREHOLDERSEQUITYPERSHARETTM",
"INTERESTDEBTPERSHARETTM",
"MARKETCAPTTM",
"ENTERPRISEVALUETTM",
"PERATIOTTM",
"PRICETOSALESRATIOTTM",
"POCFRATIOTTM",
"PFCFRATIOTTM",
"PBRATIOTTM",
"PTBRATIOTTM",
"EVTOSALESTTM",
"ENTERPRISEVALUEOVEREBITDATTM",
"EVTOOPERATINGCASHFLOWTTM",
"EVTOFREECASHFLOWTTM",
"EARNINGSYIELDTTM",
"FREECASHFLOWYIELDTTM",
"DEBTTOEQUITYTTM",
"DEBTTOASSETSTTM",
"NETDEBTTOEBITDATTM",
"CURRENTRATIOTTM",
"INTERESTCOVERAGETTM",
"INCOMEQUALITYTTM",
"DIVIDENDYIELDTTM",
"DIVIDENDYIELDPERCENTAGETTM",
"PAYOUTRATIOTTM",
"SALESGENERALANDADMINISTRATIVETOREVENUETTM",
"RESEARCHANDDEVELOPEMENTTOREVENUETTM",
"INTANGIBLESTOTOTALASSETSTTM",
"CAPEXTOOPERATINGCASHFLOWTTM",
"CAPEXTOREVENUETTM",
"CAPEXTODEPRECIATIONTTM",
"STOCKBASEDCOMPENSATIONTOREVENUETTM",
"GRAHAMNUMBERTTM",
"ROICTTM",
"RETURNONTANGIBLEASSETSTTM",
"GRAHAMNETNETTTM",
"WORKINGCAPITALTTM",
"TANGIBLEASSETVALUETTM",
"NETCURRENTASSETVALUETTM",
"INVESTEDCAPITALTTM",
"AVERAGERECEIVABLESTTM",
"AVERAGEPAYABLESTTM",
"AVERAGEINVENTORYTTM",
"DAYSSALESOUTSTANDINGTTM",
"DAYSPAYABLESOUTSTANDINGTTM",
"DAYSOFINVENTORYONHANDTTM",
"RECEIVABLESTURNOVERTTM",
"PAYABLESTURNOVERTTM",
"INVENTORYTURNOVERTTM",
"ROETTM",
"CAPEXPERSHARETTM",
"DIVIDENDPERSHARETTM",
"DEBTTOMARKETCAPTTM",
"DIVIDENDYIELTTM",
"DIVIDENDYIELPERCENTAGETTM",
"PERATIOTTM",
"PEGRATIOTTM",
"PAYOUTRATIOTTM",
"CURRENTRATIOTTM",
"QUICKRATIOTTM",
"CASHRATIOTTM",
"DAYSOFSALESOUTSTANDINGTTM",
"DAYSOFINVENTORYOUTSTANDINGTTM",
"OPERATINGCYCLETTM",
"DAYSOFPAYABLESOUTSTANDINGTTM",
"CASHCONVERSIONCYCLETTM",
"GROSSPROFITMARGINTTM",
"OPERATINGPROFITMARGINTTM",
"PRETAXPROFITMARGINTTM",
"NETPROFITMARGINTTM",
"EFFECTIVETAXRATETTM",
"RETURNONASSETSTTM",
"RETURNONEQUITYTTM",
"RETURNONCAPITALEMPLOYEDTTM",
"NETINCOMEPEREBTTTM",
"EBTPEREBITTTM",
"EBITPERREVENUETTM",
"DEBTRATIOTTM",
"DEBTEQUITYRATIOTTM",
"LONGTERMDEBTTOCAPITALIZATIONTTM",
"TOTALDEBTTOCAPITALIZATIONTTM",
"INTERESTCOVERAGETTM",
"CASHFLOWTODEBTRATIOTTM",
"COMPANYEQUITYMULTIPLIERTTM",
"RECEIVABLESTURNOVERTTM",
"PAYABLESTURNOVERTTM",
"INVENTORYTURNOVERTTM",
"FIXEDASSETTURNOVERTTM",
"ASSETTURNOVERTTM",
"OPERATINGCASHFLOWPERSHARETTM",
"FREECASHFLOWPERSHARETTM",
"CASHPERSHARETTM",
"OPERATINGCASHFLOWSALESRATIOTTM",
"FREECASHFLOWOPERATINGCASHFLOWRATIOTTM",
"CASHFLOWCOVERAGERATIOSTTM",
"SHORTTERMCOVERAGERATIOSTTM",
"CAPITALEXPENDITURECOVERAGERATIOTTM",
"DIVIDENDPAIDANDCAPEXCOVERAGERATIOTTM",
"PRICEBOOKVALUERATIOTTM",
"PRICETOBOOKRATIOTTM",
"PRICETOSALESRATIOTTM",
"PRICEEARNINGSRATIOTTM",
"PRICETOFREECASHFLOWSRATIOTTM",
"PRICETOOPERATINGCASHFLOWSRATIOTTM",
"PRICECASHFLOWRATIOTTM",
"PRICEEARNINGSTOGROWTHRATIOTTM",
"PRICESALESRATIOTTM",
"DIVIDENDYIELDTTM",
"ENTERPRISEVALUEMULTIPLETTM",
"PRICEFAIRVALUETTM",
"DIVIDENDPERSHARETTM",
"PRICE",
"CHANGESPERCENTAGE",
"CHANGE",
"DAYLOW",
"DAYHIGH",
"YEARHIGH",
"YEARLOW",
"MARKETCAP",
"PRICEAVG50",
"PRICEAVG200",
"VOLUME",
"AVGVOLUME",
"EXCHANGE",
"OPEN",
"PREVIOUSCLOSE",
"EPS",
"PE",
"EARNINGSANNOUNCEMENT",
"SHARESOUTSTANDING",
"REVENUEGROWTH",
"GROSSPROFITGROWTH",
"EBITGROWTH",
"OPERATINGINCOMEGROWTH",
"NETINCOMEGROWTH",
"EPSGROWTH",
"EPSDILUTEDGROWTH",
"WEIGHTEDAVERAGESHARESGROWTH",
"WEIGHTEDAVERAGESHARESDILUTEDGROWTH",
"DIVIDENDSPERSHAREGROWTH",
"OPERATINGCASHFLOWGROWTH",
"FREECASHFLOWGROWTH",
"TENYREVENUEGROWTHPERSHARE",
"FIVEYREVENUEGROWTHPERSHARE",
"THREEYREVENUEGROWTHPERSHARE",
"TENYOPERATINGCFGROWTHPERSHARE",
"FIVEYOPERATINGCFGROWTHPERSHARE",
"THREEYOPERATINGCFGROWTHPERSHARE",
"TENYNETINCOMEGROWTHPERSHARE",
"FIVEYNETINCOMEGROWTHPERSHARE",
"THREEYNETINCOMEGROWTHPERSHARE",
"TENYSHAREHOLDERSEQUITYGROWTHPERSHARE",
"FIVEYSHAREHOLDERSEQUITYGROWTHPERSHARE",
"THREEYSHAREHOLDERSEQUITYGROWTHPERSHARE",
"TENYDIVIDENDPERSHAREGROWTHPERSHARE",
"FIVEYDIVIDENDPERSHAREGROWTHPERSHARE",
"THREEYDIVIDENDPERSHAREGROWTHPERSHARE",
"RECEIVABLESGROWTH",
"INVENTORYGROWTH",
"ASSETGROWTH",
"BOOKVALUEPERSHAREGROWTH",
"DEBTGROWTH",
"RDEXPENSEGROWTH",
"SGAEXPENSESGROWTH",
"BETA",
"VOLAVG",
"MKTCAP",
"LASTDIV",
"RANGE",
"CHANGES",
"COMPANYNAME",
"CURRENCY",
"CIK",
"ISIN",
"CUSIP",
"EXCHANGE",
"EXCHANGESHORTNAME",
"INDUSTRY",
"WEBSITE",
"CEO",
"SECTOR",
"COUNTRY",
"FULLTIMEEMPLOYEES",
"PHONE",
"ADDRESS",
"CITY",
"STATE",
"ZIP",
"DCFDIFF",
"DCF",
]
const gando =[
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"string",
"string",
"integer",
"integer",
"integer",
"string",
"string",
"string",
"string",
"string",
"string",
"string",
"integer",
"integer",
"string",
"string",
"string",
"integer",
"integer",
"integer", 
]

 

const tableNames=[
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Key Metrics TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Financial Ratios TTM",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Real Time Quote",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Financial Growth ANN",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile",
    "All Tickers - Company Profile"]

const keyMetricsStringData =[]
const financialRatiosStringData =[]
const realTimeQuoteStringData =[]
const financialGrowthStringData=[]
const companyProfileStringData=[]

const keyMetricsIntegerData =[]
const financialRatiosIntegerData =[]
const realTimeQuoteIntegerData =[]
const financialGrowthIntegerData=[]
const companyProfileIntegerData=[]

loru.map((i,index)=>{

    switch (tableNames[index]) {
        case "All Tickers - Key Metrics TTM":
            gando[index] === "Integer" ?
            keyMetricsIntegerData.push({label:i,value:i})
    :
    keyMetricsStringData.push({label:i,value:i})
            break;
        case "All Tickers - All Tickers - Financial Ratios TTM":
            gando[index] === "Integer" ?
            financialRatiosIntegerData.push({label:i,value:i})
    :
    financialRatiosStringData.push({label:i,value:i})
            break;
        case "All Tickers - Real Time Quote":
            gando[index] === "Integer" ?
            realTimeQuoteIntegerData.push({label:i,value:i})
    :
    realTimeQuoteStringData.push({label:i,value:i})
            break;
        case "All Tickers - Financial Growth ANN":
            gando[index] === "Integer" ?
            financialGrowthStringData.push({label:i,value:i})
    :
    financialGrowthIntegerData.push({label:i,value:i})
            break;
        case "All Tickers - Company Profile":
            gando[index] === "Integer" ?
            companyProfileIntegerData.push({label:i,value:i})
    :
    companyProfileStringData.push({label:i,value:i})
            break;
     
    }
 
}) 